/*

*BEM NAMING CONVENTIONS
    *CAMEL CASE FOR THE MODIFIERS 

DIRECTIONS

- INPUT STARTING ADDRESS ✔
- INPUT DESTINATION ✔
- SUBMIT TO GET RESULTS ✔
    - DISPLAY TIME FOR BOTH OPTIONS 

PODCAST
- USER TO SUBMIT SEARCH QUERY FOR PODCAST ✔
- THEN SELECT EPISODE TO LISTEN TO 

- COMPARE RESULT TO LENGTH OF PODCAST SELECTED TO THE AVAILABLE MODES OF TRANSPORTATION
    - BIKE
    - WALK
- RECOMMEND TRAVEL METHOD
- INCLUDE DISCLAIMER FOR BIKING AND LISTENING TO A PODCAST


ERROR HANDLING 
- USER SEARCH DOESN'T PRODUCE RESULT - PODCAST OR DESTINATION ✔
- TRAVEL TIME LONGER THAN PODCAST? - WARNING YOU'LL BE ALONE WITH YOUR OWN THOUGHTS FOR XX MINUTES / WARNING BE PREPARED FOR A CLIFF HANGER
- ALERT THRESHOLD IS 5 MINUTES      
- TOO FAR TO WALK OR DRIVE - MAP QUEST WON'T PRODUCE RESULTS - DON'T ATTEMPT THIS COMMUTE!  STAY HOME
- MUST COMPLETE ALL FIELDS

STRETCH
- DISPLAY MAP
- SUGGEST OTHER PODCASTS TO LISTEN TO BASED ON INTERESTS
- INCLUDE DRIVING AND PUBLIC TRANSIT OPTIONS
- AUTO-DETECT  ADDRESS STARTING POINT
    - MAY NEED THIRD API
    - CAN WE AUTO FILL?
- PODCAST TO PLAY
*/
