/*

*BEM NAMING CONVENTIONS
    *CAMEL CASE FOR THE MODIFIERS 

USER TO SELECT PODCAST
- INPUT - MANUAL SEARCH BAR - OR -  
- SELECT - SELECT BY CATEGORY
- CHOOSE FROM TOP 10 PODCASTS - AUTO-LOAD RIGHT AWAY IN CASE THEY DON'T KNOW WHAT TO SEARCH
    - THEN SELECT EPISODE TO LISTEN TO

DIRECTIONS
- AUTO-DETECT STARTING POINT
    - CAN WE AUTO FILL?
- INPUT DESTINATION
- GET RESULT
- COMPARE RESULT TO LENGTH OF PODCAST SELECTED TO THE AVAILABLE MODES OF TRANSPORTATION
    - BIKE
    - WALK
- RECOMMEND TRAVEL METHOD
- INCLUDE DISCLAIMER FOR BIKING AND LISTENING TO A PODCAST

ERROR HANDLING 
- USER SEARCH DOESN'T PRODUCE RESULT - PODCAST OR DESTINATION
- TRAVEL TIME LONGER THAN PODCAST? - WARNING YOU'LL BE ALONE WITH YOUR OWN THOUGHTS FOR XX MINUTES / WARNING BE PREPARED FOR A CLIFF HANGER
    - ALERT THRESHOLD IS 5 MINUTES
- TOO FAR TO WALK OR DRIVE - MAP QUEST WON'T PRODUCE RESULTS


STRETCH
- DISPLAY MAP
- SUGGEST OTHER PODCASTS TO LISTEN TO BASED ON INTERESTS
- INCLUDE DRIVING AND PUBLIC TRANSIT OPTIONS


*/
